/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author nathan
 */
public class CreatePlayerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CreatePlayerGUI
     */
    public CreatePlayerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        create = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Project Demon");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name :");
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 63, 122, -1));

        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name :");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 105, 122, -1));

        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username :");
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 139, 122, -1));

        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password :");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 173, 122, -1));

        ConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPassword.setText("Confirm Password :");
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 207, -1, -1));

        Title.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Create Player");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 14, -1, -1));

        FirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FirstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 59, 120, -1));

        LastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(LastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 93, 120, -1));

        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 127, 120, -1));

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 161, 120, -1));

        ConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 195, 120, -1));

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 241, 86, -1));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 241, -1, -1));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/resources/background2.jpg"))); // NOI18N
        background2.setText("jLabel1");
        getContentPane().add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
// if enter key is pressed we assume to create
        createActionPerformed(evt);        
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void ConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldActionPerformed
// if enter key is pressed we assume to create
        createActionPerformed(evt);       
    }//GEN-LAST:event_ConfirmPasswordFieldActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // This action cancels what we currently have:
        this.dispose();
        
    }//GEN-LAST:event_CancelActionPerformed
   
   
    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // Need to do three things:
        // Check password with confirm password and make sure all blocks have been filled.
        // Note that creation doesn't check if username is already taken!
        String passText,confirmPass,fName,lName,uName,pInfo;
        passText = new String(PasswordField.getPassword());
        confirmPass = new String(ConfirmPasswordField.getPassword());
        fName = FirstNameField.getText();
        lName = LastNameField.getText();
        uName = UsernameField.getText();
        pInfo = uName + ","+ passText + ","+ fName+ "," + lName;
        // have a check class 
        if(!(passText.equals(confirmPass) && confirmPass.length() != 0))
        {
                JOptionPane.showMessageDialog(this, "Passwords don't match", "Error", 0);
                
         }
        else if(fName.length() == 0 || lName.length() == 0 || uName.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Error - All critera not met", "Error", 0);
        }
        else if( fName.contains(" ") || lName.contains(" ") || uName.contains(" "))
        {
            JOptionPane.showMessageDialog(this, "Error - Can't have spaces in names", "Error", 0);
        }
        else
        {
            // Go to the HappinessCriteria page
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Is this Correct??", "Validate" , 2 , JOptionPane.QUESTION_MESSAGE); 
            if(showConfirmDialog == 0)
            {
                new HappinessCriteria(pInfo).setVisible(true);
                this.dispose(); // Get rid of the page   
            }    
            
            
        }        
    }//GEN-LAST:event_createActionPerformed

    private void FirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameFieldActionPerformed
        // if enter key is pressed we assume to create
        createActionPerformed(evt);
    }//GEN-LAST:event_FirstNameFieldActionPerformed

    private void LastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameFieldActionPerformed
        // if enter key is pressed we assume to create
        createActionPerformed(evt);
    }//GEN-LAST:event_LastNameFieldActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
// if enter key is pressed we assume to create
        createActionPerformed(evt);
    }//GEN-LAST:event_UsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePlayerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel background2;
    private javax.swing.JButton create;
    // End of variables declaration//GEN-END:variables
   
}
