package Game;

import Player.PlayerProfile;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nathan
 */
public class StartMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartMenuGUI
     */
    public StartMenuGUI() {
        initComponents();
        Sound.musicPlay("EvilMusic.wav");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        createAccount = new javax.swing.JButton();
        start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Start Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Project Demon");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 286, 68));

        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 121, 77, -1));

        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password :");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 167, 77, -1));

        usernameField.setName(""); // NOI18N
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 115, 150, -1));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 161, 150, -1));

        createAccount.setText("Create Account");
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });
        getContentPane().add(createAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 269, -1, -1));

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 269, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game/resources/startMenu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // If enter is pressed we assume to start game
        startActionPerformed(evt);
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        // TODO add your handling code here:
        
        new CreatePlayerGUI().setVisible(true);
    }//GEN-LAST:event_createAccountActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        // 1) will  create instances of username and password.
        // 2) will check to see if criteria is met for username
        // 3) will check if username is in list
        // 4) will check if password is correct for username
        // 5) will go to gameboard
        String uName, pName,line;
        uName = usernameField.getText(); // 1
        pName = new String(passwordField.getPassword()); // 1
        System.out.println("Entered password is: " + pName);
        if (uName.length()==0) // 2
        {
            JOptionPane.showMessageDialog(this, "Missing Username", "Error", 0);
        }
        
        else
        {
           try 
           {
                BufferedReader br = new BufferedReader(new FileReader("players.txt"));
                while((line = br.readLine()) != null)
                {
                    String[] UandP = line.split(",");
                    System.out.println("uName is " + UandP[0]);
                    System.out.println("pName is " + UandP[1]);
                    if(uName.equals(UandP[0])) // 3
                    {
                        if(pName.equals(UandP[1]))// 4
                        {
                            // Set up the board and dispose of start menu and close file
                            System.out.println("We have found a match");
                            JOptionPane.showMessageDialog(this, "Welcome " + UandP[2] +" "+UandP[3], "Logged on", 1);
                            JOptionPane.showMessageDialog(this, "Happiness are: " +  "Wealth:"+ UandP[4]+ " Solitude:" +UandP[5]
                                    + " Power:" + UandP[6], line, 1); 
                            PlayerProfile login_player = new PlayerProfile(UandP[0],UandP[1],UandP[2],UandP[3]);
                            LocalPlayer.setLocalPlayer(login_player);
                            GameMain.active.addPlayer(login_player);
                            new Board.Main().setVisible(true);                        
                            this.dispose();
                            Sound.musicStop();
                            return;
                        }                         
                    }    
                }
                   br.close();
                   JOptionPane.showMessageDialog(this, "Username or Password is wrong ", "Error", 0);
                   
            
            } 
            catch (FileNotFoundException ex)
            {    
               JOptionPane.showMessageDialog(this, "No file", "Error", 0);
            }   
            
            catch (IOException ex) 
            {
               Logger.getLogger(StartMenuGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    

       // new Board.Main().setVisible(true);
       // this.dispose();

    }//GEN-LAST:event_startActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
// if enter key is pressed we assume to create
        startActionPerformed(evt);        
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenuGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton start;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
